# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_Name', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=40)),
                ('Genre', models.CharField(max_length=25)),
                ('PublicationDate', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='mySerie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1.Series'),
        ),
    ]
